#各种连接信息


#Redis连接信息
Redis:
  host : xxxx
  port : xxxx
  db : xxx
  key_LOGIN : "xxxx:"
  key_FORGET_PASSWORD : "xxxx:"
  key_SINGN_UP : "xxx"

#MySql连接信息及数据库信息
MySql:
  host : xxx
  port : xxx
  user : xxx
  password : xxx
  database_name :
    - xxx
    - xxx

#AndroidClient配置信息
AndroidClient:
  platformName : "Android"
  deviceName : "MI 9 transport_id:1"
  appPackage : "xxx"
  newCommandTimeout : 120
  apk : "xxx"
